### Завдання 1

Дати опис набору даних та звідки взятий цей набір даних. По можливості дайте посилання

Набір даних зпарсений з сайту "https://www.formula1.com/en/drivers.html" за допомогою пакету Beautiful Soup:

In [19]:
url = "https://www.formula1.com/en/drivers.html"

In [20]:
response = requests.get(url)
soup = BeautifulSoup(response.content)
table = soup.find('table')

In [21]:
driver_links = []
for i in soup.select('a[class="driver"]'):
    driver_links.append(i.get('href').split('/')[-1])

In [22]:
formula1_list = []
for i in driver_links:
    url_d = 'https://www.formula1.com/en/drivers/' + i
    response_d = requests.get(url_d)
    soup_d = BeautifulSoup(response_d.content)
    table_d = soup_d.find('table')
    biography = []
    info_d = []
    for i in soup_d.select('div[class="text parbase"] p'):
        biography.append(i.text)    
    for i in soup_d.select('td[class="stat-value"]'):
        info_d.append(i.text)
    formula1_list.append([" ".join(biography)] + info_d)

In [23]:
formula1 = pd.DataFrame(formula1_list, columns =['Biography', 'Team', 'Country', 'Podiums', 'Points', 'Grands Prix entered', 
                                                 'World Championships', 'Highest race finish', 'Highest grid position', 
                                                 'Date of birth', 'Place of birth'])
formula1

,Biography,Team,Country,Podiums,Points,Grands Prix entered,World Championships,Highest race finish,Highest grid position,Date of birth,Place of birth
0,Michael Schumacher was the undisputed king of ...,Alpine,Spain,97,1904,318,2,1 (x32),1,29/07/1981,"Oviedo, Spain"
1,Learning his craft on Finnish roads of ice and...,Mercedes,Finland,59,1559,161,N/A,1 (x9),1,28/08/1989,"Nastola, Finland"
2,If there’s one man who knows how big a rollerc...,AlphaTauri,France,2,207,68,N/A,1 (x1),4,07/02/1996,"Rouen, France"
3,He’s the Italian steed with speed from the sta...,Alfa Romeo Racing,Italy,N/A,18,44,N/A,5 (x1),7,14/12/1993,"Martina Franca, Italy"
4,‘Still I Rise’ – these are the words emblazone...,Mercedes,United Kingdom,169,3872,270,7,1 (x98),1,07/01/1985,"Stevenage, England"
5,Thirteen is an advanced age to begin your kart...,Williams,Canada,N/A,0,21,N/A,11 (x3),14,29/06/1995,"Montreal, Canada"
6,"Born in the Mediterranean idyll of Monaco, Lec...",Ferrari,Monaco,12,441,63,N/A,1 (x2),1,16/10/1997,"Monte Carlo, Monaco"
7,Nikita Mazepin might be bringing a healthy chu...,Haas F1 Team,Russian Automobile Federation,N/A,0,4,N/A,17 (x1),19,02/03/1999,"Moscow, Russia"
8,Lando Norris may not be named after Star Wars ...,McLaren,United Kingdom,2,187,42,N/A,3 (x2),3,13/11/1999,"Bristol, England"
9,If there’s one word that dominates Esteban Oco...,Alpine,France,1,208,71,N/A,2 (x1),3,17/09/1996,"Évreux, Normandy"
10,He’s the fighter with a gentle touch from the ...,Red Bull Racing,Mexico,10,738,197,N/A,1 (x1),2,26/01/1990,"Guadalajara, Mexico"
11,He’s the world-famous racing driver who just w...,Alfa Romeo Racing,Finland,103,1863,336,1,1 (x21),1,17/10/1979,"Espoo, Finland"
12,The self-styled “Honey Badger” is fuzzy on the...,McLaren,Australia,31,1183,192,N/A,1 (x7),1,01/07/1989,"Perth, Australia"
13,"He’s the driver with the motto: “If in doubt, ...",Williams,United Kingdom,N/A,3,42,N/A,9 (x1),2,15/02/1998,"King's Lynn, England"
14,He’s the matador from Madrid racing royalty. ...,Ferrari,Spain,2,392,123,N/A,2 (x1),3,01/09/1994,"Madrid, Spain"
15,Plenty of sons of former F1 drivers have joine...,Haas F1 Team,Germany,N/A,0,4,N/A,16 (x2),18,22/03/1999,"Vufflens-le-Château, Switzerland"
16,There is no such thing as too much too soon fo...,Aston Martin,Canada,3,147,82,N/A,3 (x3),1,29/10/1998,"Montreal, Canada"
17,"In the entire history of Formula 1, no Japanes...",AlphaTauri,Japan,N/A,2,4,N/A,9 (x1),13,11/05/2000,"Sagamihara, Japan"
18,"He’s Max by name, and max by nature. Arriving...",Red Bull Racing,Netherlands,46,1242,123,N/A,1 (x11),1,30/09/1997,"Hasselt, Belgium"
19,"Born and raised a Bull, then a Prancing Horse,...",Aston Martin,Germany,121,3018,262,4,1 (x53),1,03/07/1987,"Heppenheim, Germany"

In [24]:
formula1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Biography              20 non-null     object
 1   Team                   20 non-null     object
 2   Country                20 non-null     object
 3   Podiums                20 non-null     object
 4   Points                 20 non-null     object
 5   Grands Prix entered    20 non-null     object
 6   World Championships    20 non-null     object
 7   Highest race finish    20 non-null     object
 8   Highest grid position  20 non-null     object
 9   Date of birth          20 non-null     object
 10  Place of birth         20 non-null     object
dtypes: object(11)
memory usage: 1.8+ KB

### Дати опис набору даних:
Набір даних містить інформацію про автоперегони та складається з наступних атрибутів: біографія гонщиків, команда, країна, бали, чемпіонати світу, найвищий рейтинг, дата та місце народження. 
Набір має 10 атрибутів та 20 елементів.

### Завдання 2

In [12]:
import pandas as pd
import urllib.request 
import requests

In [3]:
from bs4 import BeautifulSoup
url = "http://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Frestaurants.xml"

In [4]:
response = requests.get(url)
soup = BeautifulSoup(response.content)
table = soup.find('table')

In [5]:
zip_codes = []
for i in soup.select('zipcode'):
    zip_codes.append(i.text)

In [6]:
len([i for i in zip_codes if i == '21231'])

127

### Завдання 3

Оскільки парсинг даних був проведений у завданні 1, дослідимо готовий датафрейм formula1:

### 1. Виведіть гонщиків перші 10 гонщиків дата фрейму.

In [14]:
formula1.head(0)

,Biography,Team,Country,Podiums,Points,Grands Prix entered,World Championships,Highest race finish,Highest grid position,Date of birth,Place of birth
0,Michael Schumacher was the undisputed king of ...,Alpine,Spain,97,1904,318,2,1 (x32),1,29/07/1981,"Oviedo, Spain"
1,Learning his craft on Finnish roads of ice and...,Mercedes,Finland,59,1559,161,N/A,1 (x9),1,28/08/1989,"Nastola, Finland"
2,If there’s one man who knows how big a rollerc...,AlphaTauri,France,2,207,68,N/A,1 (x1),4,07/02/1996,"Rouen, France"
3,He’s the Italian steed with speed from the sta...,Alfa Romeo Racing,Italy,N/A,18,44,N/A,5 (x1),7,14/12/1993,"Martina Franca, Italy"
4,‘Still I Rise’ – these are the words emblazone...,Mercedes,United Kingdom,169,3872,270,7,1 (x98),1,07/01/1985,"Stevenage, England"
5,Thirteen is an advanced age to begin your kart...,Williams,Canada,N/A,0,21,N/A,11 (x3),14,29/06/1995,"Montreal, Canada"
6,"Born in the Mediterranean idyll of Monaco, Lec...",Ferrari,Monaco,12,441,63,N/A,1 (x2),1,16/10/1997,"Monte Carlo, Monaco"
7,Nikita Mazepin might be bringing a healthy chu...,Haas F1 Team,Russian Automobile Federation,N/A,0,4,N/A,17 (x1),19,02/03/1999,"Moscow, Russia"
8,Lando Norris may not be named after Star Wars ...,McLaren,United Kingdom,2,187,42,N/A,3 (x2),3,13/11/1999,"Bristol, England"
9,If there’s one word that dominates Esteban Oco...,Alpine,France,1,208,71,N/A,2 (x1),3,17/09/1996,"Évreux, Normandy"
10,He’s the fighter with a gentle touch from the ...,Red Bull Racing,Mexico,10,738,197,N/A,1 (x1),2,26/01/1990,"Guadalajara, Mexico"
11,He’s the world-famous racing driver who just w...,Alfa Romeo Racing,Finland,103,1863,336,1,1 (x21),1,17/10/1979,"Espoo, Finland"
12,The self-styled “Honey Badger” is fuzzy on the...,McLaren,Australia,31,1183,192,N/A,1 (x7),1,01/07/1989,"Perth, Australia"
13,"He’s the driver with the motto: “If in doubt, ...",Williams,United Kingdom,N/A,3,42,N/A,9 (x1),2,15/02/1998,"King's Lynn, England"
14,He’s the matador from Madrid racing royalty. ...,Ferrari,Spain,2,392,123,N/A,2 (x1),3,01/09/1994,"Madrid, Spain"
15,Plenty of sons of former F1 drivers have joine...,Haas F1 Team,Germany,N/A,0,4,N/A,16 (x2),18,22/03/1999,"Vufflens-le-Château, Switzerland"
16,There is no such thing as too much too soon fo...,Aston Martin,Canada,3,147,82,N/A,3 (x3),1,29/10/1998,"Montreal, Canada"
17,"In the entire history of Formula 1, no Japanes...",AlphaTauri,Japan,N/A,2,4,N/A,9 (x1),13,11/05/2000,"Sagamihara, Japan"
18,"He’s Max by name, and max by nature. Arriving...",Red Bull Racing,Netherlands,46,1242,123,N/A,1 (x11),1,30/09/1997,"Hasselt, Belgium"
19,"Born and raised a Bull, then a Prancing Horse,...",Aston Martin,Germany,121,3018,262,4,1 (x53),1,03/07/1987,"Heppenheim, Germany"

### 2. Виведіть всх гонщиків із США.

In [13]:
formula1[formula1.Country == 'USA']

Empty DataFrame
Columns: [Biography, Team, Country, Podiums, Points, Grands Prix entered, World Championships, Highest race finish, Highest grid position, Date of birth, Place of birth]
Index: []

### 3. Скільки гонщиків брали участь у «Чемпіонаті світу».

In [70]:
len(formula1[formula1['World Championships'] != "N/A"])

4